// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.first_run", false);
user_pref("app.normandy.startupExperimentPrefs.dom.push.alwaysConnect", true);
user_pref("app.normandy.user_id", "7efdc267-cac1-430c-8957-42b0e3d717b8");
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1543842054);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1543842175);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1543841574);
user_pref("app.update.lastUpdateTime.recipe-client-addon-run", 1543841814);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1543841694);
user_pref("app.update.lastUpdateTime.services-settings-poll-changes", 1543841934);
user_pref("app.update.lastUpdateTime.telemetry_modules_ping", 1543842415);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 1543842295);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.capacity", 409600);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1543841544);
user_pref("browser.laterrun.bookkeeping.sessionCount", 1);
user_pref("browser.laterrun.enabled", true);
user_pref("browser.migration.version", 74);
user_pref("browser.newtabpage.activity-stream.impressionId", "{f6386485-22d7-4556-894a-97a9f13a40e6}");
user_pref("browser.newtabpage.activity-stream.migrationLastShownDate", 1543784400);
user_pref("browser.newtabpage.activity-stream.migrationRemainingDays", 3);
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.onboarding.notification.last-time-of-changing-tour-sec", 1543841546);
user_pref("browser.onboarding.notification.prompt-count", 1);
user_pref("browser.onboarding.notification.tour-ids-queue", "onboarding-tour-performance,onboarding-tour-private-browsing,onboarding-tour-screenshots,onboarding-tour-addons,onboarding-tour-customize,onboarding-tour-default-browser,onboarding-tour-performance,onboarding-tour-private-browsing,onboarding-tour-screenshots,onboarding-tour-addons,onboarding-tour-customize,onboarding-tour-default-browser");
user_pref("browser.onboarding.seen-tourset-version", 2);
user_pref("browser.onboarding.tour-type", "new");
user_pref("browser.pageActions.persistedActions", "{\"version\":1,\"ids\":[\"bookmark\",\"bookmarkSeparator\",\"copyURL\",\"emailLink\",\"addSearchEngine\",\"sendToDevice\",\"pocket\",\"screenshots\"],\"idsInUrlbar\":[\"pocket\",\"bookmark\"]}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.safebrowsing.provider.google4.lastupdatetime", "1543841690893");
user_pref("browser.safebrowsing.provider.google4.nextupdatetime", "1543843460893");
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1543841609525");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1543845209525");
user_pref("browser.search.region", "TR");
user_pref("browser.shell.mostRecentDateSetAsDefault", "1543841547");
user_pref("browser.slowStartup.averageTime", 4798);
user_pref("browser.slowStartup.samples", 1);
user_pref("browser.startup.homepage_override.buildID", "20181016102217");
user_pref("browser.startup.homepage_override.mstone", "63.0");
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"PersonalToolbar\":[\"personal-bookmarks\"],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"home-button\",\"customizableui-special-spring1\",\"urlbar-container\",\"customizableui-special-spring2\",\"downloads-button\",\"library-button\",\"sidebar-button\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"]},\"seen\":[\"developer-button\"],\"dirtyAreaCache\":[\"PersonalToolbar\",\"nav-bar\",\"toolbar-menubar\",\"TabsToolbar\"],\"currentVersion\":14,\"newElementCount\":2}");
user_pref("browser.urlbar.placeholderName", "Google");
user_pref("browser.urlbar.timesBeforeHidingSuggestionsHint", 2);
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1543841562085");
user_pref("devtools.onboarding.telemetry.logged", true);
user_pref("distribution.canonical.bookmarksProcessed", true);
user_pref("distribution.iniFile.exists.appversion", "63.0");
user_pref("distribution.iniFile.exists.value", true);
user_pref("dom.push.userAgentID", "96eb61f5660646169a7c53a6e93bea65");
user_pref("extensions.blocklist.lastModified", "Mon, 26 Nov 2018 14:19:56 GMT");
user_pref("extensions.blocklist.pingCountTotal", 2);
user_pref("extensions.blocklist.pingCountVersion", 2);
user_pref("extensions.databaseSchema", 27);
user_pref("extensions.getAddons.cache.lastUpdate", 1543842055);
user_pref("extensions.getAddons.databaseSchema", 5);
user_pref("extensions.lastAppVersion", "63.0");
user_pref("extensions.lastPlatformVersion", "63.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"directory\":\"{d12caa81-a4ee-4af3-8430-fc542924ed2a}\",\"addons\":{\"fxmonitor@mozilla.org\":{\"version\":\"2.8\"}}}");
user_pref("extensions.webextensions.uuids", "{\"formautofill@mozilla.org\":\"d13ef523-a6a2-4206-be34-fea6b7907cfc\",\"webcompat@mozilla.org\":\"e29aa02c-b241-4546-9e4c-44fae0660aff\",\"screenshots@mozilla.org\":\"1b11f8c1-5276-4a4b-b2d1-5ac0caf267e8\",\"fxmonitor@mozilla.org\":\"5c95650c-f011-4002-a7ce-2325d204d317\"}");
user_pref("idle.lastDailyNotification", 1543841794);
user_pref("lightweightThemes.usedThemes", "[]");
user_pref("media.gmp-gmpopenh264.abi", "x86_64-gcc3");
user_pref("media.gmp-gmpopenh264.lastUpdate", 1543841680);
user_pref("media.gmp-gmpopenh264.version", "1.6");
user_pref("media.gmp-manager.buildID", "20181016102217");
user_pref("media.gmp-manager.lastCheck", 1543841655);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("network.predictor.cleaned-up", true);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("pdfjs.previousHandler.preferredAction", 4);
user_pref("places.database.lastMaintenance", 1543841795);
user_pref("places.history.expiration.transient_current_max_pages", 112348);
user_pref("plugin.disable_full_page_plugin_for_types", "application/pdf");
user_pref("privacy.sanitize.pending", "[{\"id\":\"newtab-container\",\"itemsToClear\":[],\"options\":{}}]");
user_pref("security.sandbox.content.tempDirSuffix", "0e7f8b4c-792b-48eb-ba1d-f827a0c1826c");
user_pref("services.blocklist.addons.checked", 1543779724);
user_pref("services.blocklist.gfx.checked", 1543779724);
user_pref("services.blocklist.onecrl.checked", 1543779724);
user_pref("services.blocklist.pinning.checked", 1543779724);
user_pref("services.blocklist.plugins.checked", 1543779724);
user_pref("services.settings.clock_skew_seconds", -47);
user_pref("services.settings.last_etag", "\"1543241996691\"");
user_pref("services.settings.last_update_seconds", 1543841980);
user_pref("signon.importedFromSqlite", true);
user_pref("storage.vacuum.last.index", 0);
user_pref("storage.vacuum.last.places.sqlite", 1543841795);
user_pref("toolkit.startup.last_success", 1543841541);
user_pref("toolkit.telemetry.cachedClientID", "db204c50-f39b-4118-931e-249ffd09c6c3");
user_pref("toolkit.telemetry.previousBuildID", "20181016102217");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
